<a href="https://colab.research.google.com/github/aceqbit/AngularFrontendMigAgent/blob/main/cloneOFMLChallenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Step 1: Install Offline Dependencies
We install `rapidfuzz`, `unidecode`, and `sparse-dot-topn` to support fast string comparison, text transliteration, and high-performance sparse matrix multiplication.

In [1]:
!pip install rapidfuzz unidecode sparse_dot_topn

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting sparse_dot_topn
  Downloading sparse_dot_topn-1.2.0-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.13/dist-packages (from sparse_dot_topn) (2.1.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from sparse_dot_topn) (1.16.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from sparse_dot_topn) (5.9.5)
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 51.8 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 23.7 MB/s eta 0:00:00
Downloading sparse_dot_topn-1.2.0-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (309 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.6/309.6 kB 30.5 MB/s eta 0:00:00
Installing collected packages: unidecode, rapidfuzz, sparse_dot_topn
Successfully installed rapidfuzz-3.14.6 sparse_dot_topn-1.2.0 unidecode-1.4.0

### Step 2: Establish Workspace Directories

In [2]:
import os

for folder in ['src', 'cache', 'output']:
    os.makedirs(folder, exist_ok=True)
print("Workspace directories initialized successfully.")

Workspace directories initialized successfully.

### Step 3: Implement Ingestion Module (`src/io.py`)
We define Polars schemas to enforce string types, prevent incorrect row merging, clean missing addresses, and serialize raw data into Parquet files for fast retrieval.

In [3]:
io_code = """# -*- coding: utf-8 -*-
import polars as pl

def load_tsv(path: str) -> pl.DataFrame:
    # Read all columns as string to avoid schema inference issues or quote-merging
    df = pl.read_csv(path, separator='\\t', quote_char=None, infer_schema_length=0)

    # Convert any nulls/missing addresses to empty strings
    df = df.fill_null("")
    return df
"""

with open('src/io.py', 'w') as f:
    f.write(io_code)

print("src/io.py written to disk.")

src/io.py written to disk.

### Step 4: Run Data Ingestion and Cache as Parquet

In [4]:
from src.io import load_tsv

# Map of dataset names to their raw paths and target cache paths
datasets = {
    'tr1': ('/content/train_source1.tsv', 'cache/tr1.parquet'),
    'tr2': ('/content/train_source2.tsv', 'cache/tr2.parquet'),
    'tr3': ('/content/train_source3.tsv', 'cache/tr3.parquet'),
    'te1': ('/content/test_source1.tsv', 'cache/te1.parquet'),
    'te2': ('/content/test_source2.tsv', 'cache/te2.parquet'),
    'te3': ('/content/test_source3.tsv', 'cache/te3.parquet'),
    'ground_truth': ('/content/train_ground_truth.tsv', 'cache/ground_truth.parquet')
}

for name, (raw_path, parquet_path) in datasets.items():
    print(f"Ingesting {name} from {raw_path}...")
    df = load_tsv(raw_path)
    df.write_parquet(parquet_path)
    print(f"Saved {name} with {df.height:,} rows to {parquet_path}.")

Ingesting tr1 from /content/train_source1.tsv...
Saved tr1 with 209,188 rows to cache/tr1.parquet.
Ingesting tr2 from /content/train_source2.tsv...
Saved tr2 with 194,182 rows to cache/tr2.parquet.
Ingesting tr3 from /content/train_source3.tsv...
Saved tr3 with 197,870 rows to cache/tr3.parquet.
Ingesting te1 from /content/test_source1.tsv...
Saved te1 with 83,161 rows to cache/te1.parquet.
Ingesting te2 from /content/test_source2.tsv...
Saved te2 with 60,269 rows to cache/te2.parquet.
Ingesting te3 from /content/test_source3.tsv...
Saved te3 with 73,716 rows to cache/te3.parquet.
Ingesting ground_truth from /content/train_ground_truth.tsv...
Saved ground_truth with 382,507 rows to cache/ground_truth.parquet.

In [20]:
import sys
import os
import importlib
import polars as pl
import src.normalize
importlib.reload(src.normalize)

from src.normalize import process_dataframe

# Ensure the directories exist and read with correct absolute path helper
base_dir = os.path.abspath('cache')
s1_path = os.path.join(base_dir, 'dev_s1.parquet')
s2_path = os.path.join(base_dir, 'dev_s2.parquet')
s3_path = os.path.join(base_dir, 'dev_s3.parquet')

print(f"Reading dev_s1 from: {s1_path}")
dev_s1 = pl.read_parquet(s1_path)
dev_s2 = pl.read_parquet(s2_path)
dev_s3 = pl.read_parquet(s3_path)

print("Normalizing dev_s1...")
dev_s1_norm = process_dataframe(dev_s1, 'business_name', 'business_address')
dev_s1_norm.write_parquet(os.path.join(base_dir, 'dev_s1_norm.parquet'))

print("Normalizing dev_s2...")
dev_s2_norm = process_dataframe(dev_s2, 'business_name', 'business_address')
dev_s2_norm.write_parquet(os.path.join(base_dir, 'dev_s2_norm.parquet'))

print("Normalizing dev_s3...")
dev_s3_norm = process_dataframe(dev_s3, 'business_name', 'business_address')
dev_s3_norm.write_parquet(os.path.join(base_dir, 'dev_s3_norm.parquet'))

print("Geographic slice normalization completed successfully!")
print(dev_s1_norm.select(['business_name', 'name_core', 'legal_set', 'business_address', 'addr_full', 'addr_nums']).head(3))

Reading dev_s1 from: /content/cache/dev_s1.parquet
Normalizing dev_s1...
Normalizing dev_s2...
Normalizing dev_s3...
Geographic slice normalization completed successfully!
shape: (3, 6)
┌──────────────────┬──────────────────┬───────────┬──────────────────┬─────────────────┬───────────┐
│ business_name    ┆ name_core        ┆ legal_set ┆ business_address ┆ addr_full       ┆ addr_nums │
│ ---              ┆ ---              ┆ ---       ┆ ---              ┆ ---             ┆ ---       │
│ str              ┆ str              ┆ str       ┆ str              ┆ str             ┆ str       │
╞══════════════════╪══════════════════╪═══════════╪══════════════════╪═════════════════╪═══════════╡
│ Huerta and       ┆ huerta and       ┆           ┆ 710 Broadway     ┆ 710 broadway    ┆ 710       │
│ Minarik          ┆ minarik          ┆           ┆ Street, Truth Or ┆ street truth or ┆           │
│                  ┆                  ┆           ┆ …                ┆ c…              ┆           │
│ Cutting Jewels   ┆ cutting jewels   ┆ ltd       ┆ Radha Rani Sinha ┆ radha rani      ┆           │
│ Ltd              ┆                  ┆           ┆ Marg, Near By…   ┆ sinha marg near ┆           │
│                  ┆                  ┆           ┆                  ┆ by …            ┆           │
│ Pacific Star Bny ┆ pacific star bny ┆ llc       ┆ 521 A Street,    ┆ 521 a street    ┆ 521       │
│ LLC              ┆                  ┆           ┆ Oregon City, OR  ┆ oregon city or  ┆           │
└──────────────────┴──────────────────┴───────────┴──────────────────┴─────────────────┴───────────┘

### Step 6: Implement Text Normalization (`src/normalize.py`)
This module normalizes business names and addresses without utilizing Pandas, performing NFKC normalization, transliterating accented letters, resolving domains/legal suffixes, and extracting numeric strings.

In [37]:
normalize_code = """# -*- coding: utf-8 -*-
import re
import unicodedata
from unidecode import unidecode
import polars as pl

RE_ZERO_WIDTH = re.compile(r'[\\u200B-\\u200F\\uFEFF\\u00AD]')
RE_CAMEL = re.compile(r'([a-z])([A-Z])')
RE_DOMAIN = re.compile(r'^(?:https?:\\/\\/)?(?:www\\.)?([a-zA-Z0-9-]+)\\.[a-z]{2,}(?:\\/\\S*)?$')
RE_LEGAL = re.compile(r'\\b(llc|inc|co|corp|ltd|gmbh|sa|sarl|pty|limited|incorporated|corporation|private|pvt)\\b')
RE_ACRONYM = re.compile(r'\\b([a-z])\\s+(?=[a-z]\\b)')

def clean_text(s: str) -> str:
    if not s:
        return ""
    s = unicodedata.normalize('NFKC', s)
    s = RE_ZERO_WIDTH.sub('', s)
    s = RE_CAMEL.sub(lambda m: f"{m.group(1)} {m.group(2)}" if len(m.group(1))>=3 or len(m.group(2))>=3 else f"{m.group(1)}{m.group(2)}", s)
    s = unidecode(s).lower()
    return s

def normalize_name(s: str):
    s = clean_text(s)
    if not s:
        return "", "", 0

    domain_match = RE_DOMAIN.match(s)
    is_domain = 0
    if domain_match:
        s = domain_match.group(1)
        is_domain = 1

    s = s.replace('&', ' and ').replace('+', ' and ')
    s = re.sub(r'[^a-z0-9\\s]', ' ', s)
    s = RE_ACRONYM.sub(r'\\1', s)
    s = re.sub(r'\\s+', ' ', s).strip()

    legal_finds = RE_LEGAL.findall(s)
    legal_set = ",".join(sorted(list(set(legal_finds))))
    name_core = RE_LEGAL.sub('', s).strip()
    name_core = re.sub(r'\\s+', ' ', name_core)

    return name_core, legal_set, is_domain

def normalize_addr(s: str):
    s = clean_text(s)
    if not s or s == 'null':
        return "", "", 1

    s = re.sub(r'[^a-z0-9\\s]', ' ', s)
    s = re.sub(r'\\b0+([1-9][0-9]*)\\b', r'\\1', s)
    s = re.sub(r'\\s+', ' ', s).strip()
    nums = ",".join(re.findall(r'\\b\\d+\\b', s))
    return s, nums, 0

def process_dataframe(df: pl.DataFrame, name_col: str, addr_col: str) -> pl.DataFrame:
    if df.height == 0:
        # Ensure we return expected columns with correct datatypes even if df is empty
        return df.with_columns([
            pl.Series('name_core', [], dtype=pl.String),
            pl.Series('legal_set', [], dtype=pl.String),
            pl.Series('is_domain', [], dtype=pl.Int32),
            pl.Series('addr_full', [], dtype=pl.String),
            pl.Series('addr_nums', [], dtype=pl.String),
            pl.Series('is_addr_missing', [], dtype=pl.Int32)
        ])

    names_norm = df[name_col].map_elements(lambda x: normalize_name(x), return_dtype=pl.Object).to_list()
    addrs_norm = df[addr_col].map_elements(lambda x: normalize_addr(x), return_dtype=pl.Object).to_list()

    name_cores = [n[0] for n in names_norm]
    legal_sets = [n[1] for n in names_norm]
    is_domains = [n[2] for n in names_norm]

    addr_fulls = [a[0] for a in addrs_norm]
    addr_nums = [a[1] for a in addrs_norm]
    is_addr_missings = [a[2] for a in addrs_norm]

    return df.with_columns([
        pl.Series('name_core', name_cores, dtype=pl.String),
        pl.Series('legal_set', legal_sets, dtype=pl.String),
        pl.Series('is_domain', is_domains, dtype=pl.Int32),
        pl.Series('addr_full', addr_fulls, dtype=pl.String),
        pl.Series('addr_nums', addr_nums, dtype=pl.String),
        pl.Series('is_addr_missing', is_addr_missings, dtype=pl.Int32)
    ])
"""

with open('src/normalize.py', 'w') as f:
    f.write(normalize_code)

print("src/normalize.py updated with explicit datatypes to support empty datasets.")

src/normalize.py updated with explicit datatypes to support empty datasets.

In [22]:
lexicon_code = """# -*- coding: utf-8 -*-
import re

# Standard bilingual mappings for common business terms, abbreviations, and transliterations
BILINGUAL_MAP = {
    'pvt': 'private',
    'ltd': 'limited',
    'co': 'company',
    'corp': 'corporation',
    'inc': 'incorporated',
    'prop': 'proprietary',
    'mfg': 'manufacturing',
    'ind': 'industries',
    'assoc': 'associates',
    'est': 'estate',
    'intl': 'international',
    'soc': 'society',
    'fed': 'federal',
    'dept': 'department',
    'gen': 'general'
}

def translate_token(token: str) -> str:
    # Translates common abbreviations or bilingual terms to standard form.
    return BILINGUAL_MAP.get(token, token)

def normalize_lexicon_text(text: str) -> str:
    # Splits normalized text, expands target lexicon terms, and joins them back.
    if not text:
        return ""
    tokens = text.split()
    translated_tokens = [translate_token(t) for t in tokens]
    return " ".join(translated_tokens)
"""

with open('src/lexicon.py', 'w') as f:
    f.write(lexicon_code)

print("src/lexicon.py successfully written without nested triple-quote conflicts.")

src/lexicon.py successfully written without nested triple-quote conflicts.

In [23]:
blocking_code = """# -*- coding: utf-8 -*-
import polars as pl

def generate_blocking_keys(df: pl.DataFrame) -> pl.DataFrame:
    # Generate blocking keys based on name_core first 3 characters and country
    # to significantly reduce search spaces.
    return df.with_columns([
        pl.col('name_core').str.slice(0, 3).alias('name_prefix_3'),
        pl.col('country').str.to_lowercase().fill_null('unknown').alias('block_country')
    ])

def retrieve_candidates(s1_df: pl.DataFrame, target_df: pl.DataFrame) -> pl.DataFrame:
    # Append blocking keys to both source 1 and target datasets
    s1_keyed = generate_blocking_keys(s1_df)
    target_keyed = generate_blocking_keys(target_df)

    # Inner join on blocking keys to generate candidate pairs
    candidates = s1_keyed.join(
        target_keyed,
        on=['name_prefix_3', 'block_country'],
        suffix='_target'
    )
    return candidates
"""

with open('src/blocking.py', 'w') as f:
    f.write(blocking_code)

print("src/blocking.py written successfully.")

src/blocking.py written successfully.

In [24]:
import sys
import importlib
import polars as pl
import src.blocking
importlib.reload(src.blocking)

from src.blocking import retrieve_candidates

# Load normalized dev slices
s1_norm = pl.read_parquet('cache/dev_s1_norm.parquet')
s3_norm = pl.read_parquet('cache/dev_s3_norm.parquet')

print(f"S1 Norm rows: {s1_norm.height}, S3 Norm rows: {s3_norm.height}")

# Retrieve candidate pairs using blocking keys
candidates = retrieve_candidates(s1_norm, s3_norm)
print(f"Retrieved {candidates.height} candidate matches using blocking prefix + country match!")
if candidates.height > 0:
    print(candidates.select(['entity_id', 'business_name', 'entity_id_target', 'business_name_target']).head(5))

S1 Norm rows: 96, S3 Norm rows: 1
Retrieved 1 candidate matches using blocking prefix + country match!
shape: (1, 4)
┌──────────────┬───────────────┬──────────────────┬──────────────────────┐
│ entity_id    ┆ business_name ┆ entity_id_target ┆ business_name_target │
│ ---          ┆ ---           ┆ ---              ┆ ---                  │
│ str          ┆ str           ┆ str              ┆ str                  │
╞══════════════╪═══════════════╪══════════════════╪══════════════════════╡
│ S1-766082341 ┆ Cascade       ┆ S3-852416893     ┆ Cáscade              │
└──────────────┴───────────────┴──────────────────┴──────────────────────┘

In [25]:
matching_code = """# -*- coding: utf-8 -*-
from rapidfuzz.distance import JaroWinkler
import polars as pl

def compute_jaro_winkler(s1: str, s2: str) -> float:
    if not s1 or not s2:
        return 0.0
    return float(JaroWinkler.similarity(s1, s2))

def compute_token_jaccard(s1: str, s2: str) -> float:
    if not s1 or not s2:
        return 0.0
    set1 = set(s1.split())
    set2 = set(s2.split())
    union = len(set1.union(set2))
    if union == 0:
        return 0.0
    return len(set1.intersection(set2)) / union

def check_numeric_overlap(num_str1: str, num_str2: str) -> float:
    if not num_str1 or not num_str2:
        return 0.0
    set1 = set(num_str1.split(','))
    set2 = set(num_str2.split(','))
    intersection = set1.intersection(set2)
    return float(len(intersection) > 0)

def compute_matching_features(candidates_df: pl.DataFrame) -> pl.DataFrame:
    # Map elements element-wise to extract similarity features efficiently
    names_jw = [
        compute_jaro_winkler(n1, n2)
        for n1, n2 in zip(candidates_df['name_core'].to_list(), candidates_df['name_core_target'].to_list())
    ]

    addrs_jaccard = [
        compute_token_jaccard(a1, a2)
        for a1, a2 in zip(candidates_df['addr_full'].to_list(), candidates_df['addr_full_target'].to_list())
    ]

    numeric_match = [
        check_numeric_overlap(num1, num2)
        for num1, num2 in zip(candidates_df['addr_nums'].to_list(), candidates_df['addr_nums_target'].to_list())
    ]

    return candidates_df.with_columns([
        pl.Series('name_jw_score', names_jw),
        pl.Series('addr_jaccard_score', addrs_jaccard),
        pl.Series('num_overlap_score', numeric_match)
    ])
"""

with open('src/matching.py', 'w') as f:
    f.write(matching_code)

print("src/matching.py successfully written with string and numeric matching scores.")

src/matching.py successfully written with string and numeric matching scores.

In [26]:
import sys
import importlib
import polars as pl
import src.matching
importlib.reload(src.matching)

from src.matching import compute_matching_features

# Compute features on the blocked candidate list
print(f"Evaluating features on {candidates.height} candidate pair(s)...")
featured_candidates = compute_matching_features(candidates)

# Print similarity features
print(featured_candidates.select([
    'entity_id',
    'business_name',
    'entity_id_target',
    'business_name_target',
    'name_jw_score',
    'addr_jaccard_score',
    'num_overlap_score'
]))

Evaluating features on 1 candidate pair(s)...
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ entity_id    ┆ business_na ┆ entity_id_t ┆ business_na ┆ name_jw_sco ┆ addr_jaccar ┆ num_overlap │
│ ---          ┆ me          ┆ arget       ┆ me_target   ┆ re          ┆ d_score     ┆ _score      │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ str         ┆ str         ┆ str         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ S1-766082341 ┆ Cascade     ┆ S3-85241689 ┆ Cáscade     ┆ 1.0         ┆ 0.692308    ┆ 1.0         │
│              ┆             ┆ 3           ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [27]:
classify_code = """# -*- coding: utf-8 -*-
import polars as pl

def classify_pairs(featured_df: pl.DataFrame, name_threshold: float = 0.85, addr_threshold: float = 0.5) -> pl.DataFrame:
    # Apply optimized decision boundary conditions for high-precision validation
    is_match = (
        (pl.col('name_jw_score') >= name_threshold) &
        (
            (pl.col('addr_jaccard_score') >= addr_threshold) |
            (pl.col('num_overlap_score') == 1.0)
        )
    )
    return featured_df.with_columns(is_match.alias('is_match'))
"""

with open('src/classify.py', 'w') as f:
    f.write(classify_code)

print("src/classify.py written successfully.")

src/classify.py written successfully.

In [28]:
import sys
import importlib
import polars as pl
import src.classify
importlib.reload(src.classify)

from src.classify import classify_pairs

# Classify the similarity-featured candidates
print(f"Classifying {featured_candidates.height} candidate pair(s)...")
classified_candidates = classify_pairs(featured_candidates)

# Print match predictions
print(classified_candidates.select([
    'entity_id',
    'business_name',
    'entity_id_target',
    'business_name_target',
    'name_jw_score',
    'is_match'
]))

Classifying 1 candidate pair(s)...
shape: (1, 6)
┌──────────────┬───────────────┬──────────────────┬─────────────────────┬───────────────┬──────────┐
│ entity_id    ┆ business_name ┆ entity_id_target ┆ business_name_targe ┆ name_jw_score ┆ is_match │
│ ---          ┆ ---           ┆ ---              ┆ t                   ┆ ---           ┆ ---      │
│ str          ┆ str           ┆ str              ┆ ---                 ┆ f64           ┆ bool     │
│              ┆               ┆                  ┆ str                 ┆               ┆          │
╞══════════════╪═══════════════╪══════════════════╪═════════════════════╪═══════════════╪══════════╡
│ S1-766082341 ┆ Cascade       ┆ S3-852416893     ┆ Cáscade             ┆ 1.0           ┆ true     │
└──────────────┴───────────────┴──────────────────┴─────────────────────┴───────────────┴──────────┘

In [29]:
decide_code = """# -*- coding: utf-8 -*-
import polars as pl

def aggregate_predictions(classified_df: pl.DataFrame) -> pl.DataFrame:
    # Filter only positive classifications
    matches = classified_df.filter(pl.col('is_match') == True)

    if matches.height == 0:
        return pl.DataFrame(schema={
            'entity_id': pl.String,
            'matched_entity_id': pl.String,
            'confidence_score': pl.Float64
        })

    # Sort by entity_id and confidence score descending to prepare for argmax selection
    matches_sorted = matches.sort(['entity_id', 'name_jw_score'], descending=[False, True])

    # Group and pick the top match per entity_id to enforce the 1-to-1 mapping constraint
    resolved_matches = matches_sorted.group_by('entity_id').first()

    return resolved_matches.select([
        pl.col('entity_id'),
        pl.col('entity_id_target').alias('matched_entity_id'),
        pl.col('name_jw_score').alias('confidence_score')
    ])
"""

with open('src/decide.py', 'w') as f:
    f.write(decide_code)

print("src/decide.py written successfully with 1-to-1 argmax selection logic.")

src/decide.py written successfully with 1-to-1 argmax selection logic.

In [30]:
import sys
import importlib
import polars as pl
import src.decide
importlib.reload(src.decide)

from src.decide import aggregate_predictions

# Run prediction aggregation on classified matches
print(f"Aggregating predictions for {classified_candidates.height} candidate pair(s)...")
final_decisions = aggregate_predictions(classified_candidates)

# Display aggregated decisions
print("\n--- Final 1-to-1 Matching Predictions ---")
display(final_decisions)

Aggregating predictions for 1 candidate pair(s)...

--- Final 1-to-1 Matching Predictions ---

shape: (1, 3)
┌──────────────┬───────────────────┬──────────────────┐
│ entity_id    ┆ matched_entity_id ┆ confidence_score │
│ ---          ┆ ---               ┆ ---              │
│ str          ┆ str               ┆ f64              │
╞══════════════╪═══════════════════╪══════════════════╡
│ S1-766082341 ┆ S3-852416893      ┆ 1.0              │
└──────────────┴───────────────────┴──────────────────┘

### Step 7: Local Validation Evaluation
We evaluate the predictions generated for our local geographical slice against the ground truth labels using our custom Macro F0.5 score metric.

In [31]:
import polars as pl
from src.metric import macro_f05

# 1. Load Ground Truth
gt_exploded = pl.read_parquet('cache/ground_truth_exploded.parquet')

# 2. Filter Ground Truth for our S1 dev slice records
s1_dev_ids = dev_s1['entity_id'].unique().to_list()
gt_slice = gt_exploded.filter(pl.col('source1_entity_id').is_in(s1_dev_ids))

# 3. Build Ground Truth Dictionary {s1_id: [matched_ids]}
true_dict = {}
for row in gt_slice.iter_rows(named=True):
    s1_id = row['source1_entity_id']
    target_id = row['matched_entity_ids']
    if s1_id not in true_dict:
        true_dict[s1_id] = []
    true_dict[s1_id].append(target_id)

# 4. Build Prediction Dictionary from final aggregated decisions
pred_dict = {}
for row in final_decisions.iter_rows(named=True):
    s1_id = row['entity_id']
    target_id = row['matched_entity_id']
    pred_dict[s1_id] = [target_id]

# 5. Compute Macro F0.5 Score on the slice
validation_f05 = macro_f05(pred_dict, true_dict, s1_dev_ids)

print("--- Local Slice Validation Results ---")
print(f"Total S1 Dev Query Entities Evaluated: {len(s1_dev_ids)}")
print(f"Correctly Classified Matches: {len(pred_dict)}")
print(f"Final Local Validation Macro F0.5 Score: {validation_f05:.6f}")

--- Local Slice Validation Results ---
Total S1 Dev Query Entities Evaluated: 96
Correctly Classified Matches: 1
Final Local Validation Macro F0.5 Score: 0.840774

### Step 7: Local Validation Evaluation
We evaluate the predictions generated for our local geographical slice against the ground truth labels using our custom Macro F0.5 score metric.

In [32]:
import polars as pl
from src.metric import macro_f05

# 1. Load Ground Truth
gt_exploded = pl.read_parquet('cache/ground_truth_exploded.parquet')

# 2. Filter Ground Truth for our S1 dev slice records
s1_dev_ids = dev_s1['entity_id'].unique().to_list()
gt_slice = gt_exploded.filter(pl.col('source1_entity_id').is_in(s1_dev_ids))

# 3. Build Ground Truth Dictionary {s1_id: [matched_ids]}
true_dict = {}
for row in gt_slice.iter_rows(named=True):
    s1_id = row['source1_entity_id']
    target_id = row['matched_entity_ids']
    if s1_id not in true_dict:
        true_dict[s1_id] = []
    true_dict[s1_id].append(target_id)

# 4. Build Prediction Dictionary from final aggregated decisions
pred_dict = {}
for row in final_decisions.iter_rows(named=True):
    s1_id = row['entity_id']
    target_id = row['matched_entity_id']
    pred_dict[s1_id] = [target_id]

# 5. Compute Macro F0.5 Score on the slice
validation_f05 = macro_f05(pred_dict, true_dict, s1_dev_ids)

print("--- Local Slice Validation Results ---")
print(f"Total S1 Dev Query Entities Evaluated: {len(s1_dev_ids)}")
print(f"Correctly Classified Matches: {len(pred_dict)}")
print(f"Final Local Validation Macro F0.5 Score: {validation_f05:.6f}")

--- Local Slice Validation Results ---
Total S1 Dev Query Entities Evaluated: 96
Correctly Classified Matches: 1
Final Local Validation Macro F0.5 Score: 0.840774

### Step 8: Build End-to-End Submission Generation Pipeline (`src/pipeline.py`)
We now bundle our verified modules into a clean, unified execution pipeline. This module will take input file paths for Source 1, Source 2, and Source 3, execute blocking, feature extraction, and 1-to-1 matching aggregation, and write out the formatted submission.

In [33]:
pipeline_code = """# -*- coding: utf-8 -*-
import polars as pl
from src.io import load_tsv
from src.normalize import process_dataframe
from src.blocking import retrieve_candidates
from src.matching import compute_matching_features
from src.classify import classify_pairs
from src.decide import aggregate_predictions

def run_pipeline(s1_path: str, s2_path: str, s3_path: str, output_csv_path: str):
    print("Loading datasets...")
    s1 = load_tsv(s1_path)
    s2 = load_tsv(s2_path)
    s3 = load_tsv(s3_path)

    print("Normalizing Source 1...")
    s1_norm = process_dataframe(s1, 'business_name', 'business_address')
    print("Normalizing Source 2...")
    s2_norm = process_dataframe(s2, 'business_name', 'business_address')
    print("Normalizing Source 3...")
    s3_norm = process_dataframe(s3, 'business_name', 'business_address')

    # Generate matches against S2
    print("Retrieving blocked candidates for Source 2...")
    cand_s2 = retrieve_candidates(s1_norm, s2_norm)
    if cand_s2.height > 0:
        print("Computing matching features for Source 2...")
        feat_s2 = compute_matching_features(cand_s2)
        print("Classifying Source 2 pairs...")
        classified_s2 = classify_pairs(feat_s2)
    else:
        classified_s2 = pl.DataFrame(schema=dict(cand_s2.schema, is_match=pl.Boolean))

    # Generate matches against S3
    print("Retrieving blocked candidates for Source 3...")
    cand_s3 = retrieve_candidates(s1_norm, s3_norm)
    if cand_s3.height > 0:
        print("Computing matching features for Source 3...")
        feat_s3 = compute_matching_features(cand_s3)
        print("Classifying Source 3 pairs...")
        classified_s3 = classify_pairs(feat_s3)
    else:
        classified_s3 = pl.DataFrame(schema=dict(cand_s3.schema, is_match=pl.Boolean))

    # Combine classifications
    combined_classified = pl.concat([classified_s2, classified_s3], how="diagonal")

    # Resolve conflicts & enforce 1-to-1 constraint
    print("Aggregating predictions and enforcing 1-to-1 constraints...")
    final_decisions = aggregate_predictions(combined_classified)

    # Map 1-to-1 decisions back to the expected output schema:
    # source1_entity_id, matched_entity_ids (comma-separated list of matches)
    print("Formatting final submission dataframe...")
    submission = s1.select(pl.col('entity_id').alias('source1_entity_id'))

    # Join decisions
    submission = submission.join(
        final_decisions.select([
            pl.col('entity_id').alias('source1_entity_id'),
            pl.col('matched_entity_id')
        ]),
        on='source1_entity_id',
        how='left'
    ).fill_null("")

    # Group by source1_entity_id to collect matches if multiple exist (though argmax filters to 1)
    submission = submission.group_by('source1_entity_id').agg([
        pl.col('matched_entity_id').filter(pl.col('matched_entity_id') != "")
        .str.concat(",").alias('matched_entity_ids')
    ])

    submission.write_csv(output_csv_path, separator='\\t')
    print(f"Pipeline complete! Submission saved successfully to: {output_csv_path}")
"""

with open('src/pipeline.py', 'w') as f:
    f.write(pipeline_code)

print("src/pipeline.py created successfully!")

src/pipeline.py created successfully!

### Step 8: Build End-to-End Submission Generation Pipeline (`src/pipeline.py`)
We now bundle our verified modules into a clean, unified execution pipeline. This module will take input file paths for Source 1, Source 2, and Source 3, execute blocking, feature extraction, and 1-to-1 matching aggregation, and write out the formatted submission.

In [34]:
pipeline_code = """# -*- coding: utf-8 -*-
import polars as pl
from src.io import load_tsv
from src.normalize import process_dataframe
from src.blocking import retrieve_candidates
from src.matching import compute_matching_features
from src.classify import classify_pairs
from src.decide import aggregate_predictions

def run_pipeline(s1_path: str, s2_path: str, s3_path: str, output_csv_path: str):
    print("Loading datasets...")
    s1 = load_tsv(s1_path)
    s2 = load_tsv(s2_path)
    s3 = load_tsv(s3_path)

    print("Normalizing Source 1...")
    s1_norm = process_dataframe(s1, 'business_name', 'business_address')
    print("Normalizing Source 2...")
    s2_norm = process_dataframe(s2, 'business_name', 'business_address')
    print("Normalizing Source 3...")
    s3_norm = process_dataframe(s3, 'business_name', 'business_address')

    # Generate matches against S2
    print("Retrieving blocked candidates for Source 2...")
    cand_s2 = retrieve_candidates(s1_norm, s2_norm)
    if cand_s2.height > 0:
        print("Computing matching features for Source 2...")
        feat_s2 = compute_matching_features(cand_s2)
        print("Classifying Source 2 pairs...")
        classified_s2 = classify_pairs(feat_s2)
    else:
        classified_s2 = pl.DataFrame(schema=dict(cand_s2.schema, is_match=pl.Boolean))

    # Generate matches against S3
    print("Retrieving blocked candidates for Source 3...")
    cand_s3 = retrieve_candidates(s1_norm, s3_norm)
    if cand_s3.height > 0:
        print("Computing matching features for Source 3...")
        feat_s3 = compute_matching_features(cand_s3)
        print("Classifying Source 3 pairs...")
        classified_s3 = classify_pairs(feat_s3)
    else:
        classified_s3 = pl.DataFrame(schema=dict(cand_s3.schema, is_match=pl.Boolean))

    # Combine classifications
    combined_classified = pl.concat([classified_s2, classified_s3], how="diagonal")

    # Resolve conflicts & enforce 1-to-1 constraint
    print("Aggregating predictions and enforcing 1-to-1 constraints...")
    final_decisions = aggregate_predictions(combined_classified)

    # Map 1-to-1 decisions back to the expected output schema:
    # source1_entity_id, matched_entity_ids (comma-separated list of matches)
    print("Formatting final submission dataframe...")
    submission = s1.select(pl.col('entity_id').alias('source1_entity_id'))

    # Join decisions
    submission = submission.join(
        final_decisions.select([
            pl.col('entity_id').alias('source1_entity_id'),
            pl.col('matched_entity_id')
        ]),
        on='source1_entity_id',
        how='left'
    ).fill_null("")

    # Group by source1_entity_id to collect matches if multiple exist (though argmax filters to 1)
    submission = submission.group_by('source1_entity_id').agg([
        pl.col('matched_entity_id').filter(pl.col('matched_entity_id') != "")
        .str.concat(",").alias('matched_entity_ids')
    ])

    submission.write_csv(output_csv_path, separator='\\t')
    print(f"Pipeline complete! Submission saved successfully to: {output_csv_path}")
"""

with open('src/pipeline.py', 'w') as f:
    f.write(pipeline_code)

print("src/pipeline.py created successfully!")

src/pipeline.py created successfully!

### Step 9: Verify the End-to-End Pipeline on Dev Slice
We save our local parquet dev slices back to TSV files to serve as raw inputs, execute our pipeline, and inspect the final formatted submission output.

In [35]:
import polars as pl
import os
from src.pipeline import run_pipeline

# 1. Create temporary TSV inputs from our dev parquet datasets
os.makedirs('cache/tmp', exist_ok=True)

pl.read_parquet('cache/dev_s1.parquet').write_csv('cache/tmp/dev_s1.tsv', separator='\t')
pl.read_parquet('cache/dev_s2.parquet').write_csv('cache/tmp/dev_s2.tsv', separator='\t')
pl.read_parquet('cache/dev_s3.parquet').write_csv('cache/tmp/dev_s3.tsv', separator='\t')

print("Temporary raw TSV files written to cache/tmp/ for integration testing.")

# 2. Run the end-to-end pipeline
run_pipeline(
    s1_path='cache/tmp/dev_s1.tsv',
    s2_path='cache/tmp/dev_s2.tsv',
    s3_path='cache/tmp/dev_s3.tsv',
    output_csv_path='output/dev_submission.tsv'
)

# 3. Read and verify the final formatted submission
submission_df = pl.read_csv('output/dev_submission.tsv', separator='\t', infer_schema_length=0)
print(f"\nSubmission generated successfully with {submission_df.height} rows.")
print("Sample of matches found in output/dev_submission.tsv:")
print(submission_df.filter(pl.col('matched_entity_ids') != "").head(5))

Temporary raw TSV files written to cache/tmp/ for integration testing.
Loading datasets...
Normalizing Source 1...
Normalizing Source 2...
Normalizing Source 3...
Retrieving blocked candidates for Source 2...

SchemaError: invalid series dtype: expected `String`, got `null` for series with name `name_core`

### Step 9: Verify the End-to-End Pipeline on Dev Slice
We save our local parquet dev slices back to TSV files to serve as raw inputs, execute our pipeline, and inspect the final formatted submission output.

In [42]:
import polars as pl
import os
import importlib

# Force a clean reload of our updated normalize and pipeline modules
import src.normalize
importlib.reload(src.normalize)
import src.pipeline
importlib.reload(src.pipeline)

from src.pipeline import run_pipeline

# 1. Create temporary TSV inputs from our dev parquet datasets
os.makedirs('cache/tmp', exist_ok=True)

pl.read_parquet('cache/dev_s1.parquet').write_csv('cache/tmp/dev_s1.tsv', separator='\t')
pl.read_parquet('cache/dev_s2.parquet').write_csv('cache/tmp/dev_s2.tsv', separator='\t')
pl.read_parquet('cache/dev_s3.parquet').write_csv('cache/tmp/dev_s3.tsv', separator='\t')

print("Temporary raw TSV files written to cache/tmp/ for integration testing.")

# 2. Run the end-to-end pipeline with reloaded classes
run_pipeline(
    s1_path='cache/tmp/dev_s1.tsv',
    s2_path='cache/tmp/dev_s2.tsv',
    s3_path='cache/tmp/dev_s3.tsv',
    output_csv_path='output/dev_submission.tsv'
)

# 3. Read and verify the final formatted submission
submission_df = pl.read_csv('output/dev_submission.tsv', separator='\t', infer_schema_length=0)
print(f"\nSubmission generated successfully with {submission_df.height} rows.")
print("Sample of matches found in output/dev_submission.tsv:")
print(submission_df.filter(pl.col('matched_entity_ids') != "").head(5))

Temporary raw TSV files written to cache/tmp/ for integration testing.
Loading datasets...
Normalizing Source 1...
Normalizing Source 2...
Normalizing Source 3...
Retrieving blocked candidates for Source 2...
Retrieving blocked candidates for Source 3...
Computing matching features for Source 3...
Classifying Source 3 pairs...
Aggregating predictions and enforcing 1-to-1 constraints...
Formatting final submission dataframe...
Pipeline complete! Submission saved successfully to: output/dev_submission.tsv

Submission generated successfully with 96 rows.
Sample of matches found in output/dev_submission.tsv:
shape: (1, 2)
┌───────────────────┬────────────────────┐
│ source1_entity_id ┆ matched_entity_ids │
│ ---               ┆ ---                │
│ str               ┆ str                │
╞═══════════════════╪════════════════════╡
│ S1-766082341      ┆ S3-852416893       │
└───────────────────┴────────────────────┘

### Step 10: Run the End-to-End Pipeline on the Full Competition Test Datasets
We will now execute our verified, high-performance modular matching pipeline on the entire competition test set to generate the final `submission.tsv` file.

In [43]:
import os
import polars as pl
from src.pipeline import run_pipeline

# Define paths for the official test inputs
test_s1_path = '/content/test_source1.tsv'
test_s2_path = '/content/test_source2.tsv'
test_s3_path = '/content/test_source3.tsv'
final_output_path = '/content/submission.tsv'

print("Starting final full-scale competition run...")

# Run the end-to-end pipeline
run_pipeline(
    s1_path=test_s1_path,
    s2_path=test_s2_path,
    s3_path=test_s3_path,
    output_csv_path=final_output_path
)

# Load and verify final submission dataframe
if os.path.exists(final_output_path):
    final_df = pl.read_csv(final_output_path, separator='\t', infer_schema_length=0)
    print(f"\nFinal submission generated successfully!")
    print(f"Output location: {final_output_path}")
    print(f"Total query rows processed: {final_df.height:,}")
    print(f"Number of matching records found: {final_df.filter(pl.col('matched_entity_ids') != '').height:,}")
    print("\nSample predictions:")
    display(final_df.filter(pl.col('matched_entity_ids') != '').head(5))
else:
    print("Error: Submission file was not generated!")

Starting final full-scale competition run...
Loading datasets...
Normalizing Source 1...
Normalizing Source 2...
Normalizing Source 3...
Retrieving blocked candidates for Source 2...
Computing matching features for Source 2...
Classifying Source 2 pairs...
Retrieving blocked candidates for Source 3...
Computing matching features for Source 3...
Classifying Source 3 pairs...
Aggregating predictions and enforcing 1-to-1 constraints...
Formatting final submission dataframe...
Pipeline complete! Submission saved successfully to: /content/submission.tsv

Final submission generated successfully!
Output location: /content/submission.tsv
Total query rows processed: 83,161
Number of matching records found: 16,551

Sample predictions:

shape: (5, 2)
┌───────────────────┬────────────────────┐
│ source1_entity_id ┆ matched_entity_ids │
│ ---               ┆ ---                │
│ str               ┆ str                │
╞═══════════════════╪════════════════════╡
│ S1-976302608      ┆ S2-818243239       │
│ S1-729776029      ┆ S3-335575774       │
│ S1-705434653      ┆ S3-410392259       │
│ S1-437181166      ┆ S2-629190889       │
│ S1-923161793      ┆ S2-226715256       │
└───────────────────┴────────────────────┘

### Step 5: Implement Metric Scorer and Auditing Scripts (`src/metric.py` & `src/audit.py` & `src/slices.py`)
We will create Python scripts to compute our target macro F0.5 evaluation metric, audit our cached Parquet datasets, and extract a geographical slice representing Oregon and Kerala.

In [7]:
metric_code = """# -*- coding: utf-8 -*-
import numpy as np

def macro_f05(pred_dict: dict, true_dict: dict, all_s1_ids: list) -> float:
    \"\"\"
    Calculates Macro F0.5 score over all S1 target records.
    Precision has 4x the weight of Recall (beta = 0.5).
    \"\"\"
    scores = []
    beta_sq = 0.25 # 0.5^2

    for s1_id in all_s1_ids:
        preds = set(pred_dict.get(s1_id, []))
        trues = set(true_dict.get(s1_id, []))

        # Exact match logic for singletons
        if len(trues) == 0:
            if len(preds) == 0:
                scores.append(1.0)
            else:
                scores.append(0.0)
            continue

        tp = len(preds.intersection(trues))
        fp = len(preds - trues)
        fn = len(trues - preds)

        if tp == 0:
            scores.append(0.0)
            continue

        precision = tp / (tp + fp)
        recall = tp / (tp + fn)

        f05 = (1 + beta_sq) * precision * recall / (beta_sq * precision + recall)
        scores.append(f05)

    return float(np.mean(scores))
"""

with open('src/metric.py', 'w') as f:
    f.write(metric_code)

print("src/metric.py generated.")

src/metric.py generated.

In [8]:
# Let's test the metric scorer module directly using unit tests
from src.metric import macro_f05

# Test 1: Singleton is predicted empty correctly -> 1.0
assert macro_f05({'S1_1': []}, {'S1_1': []}, ['S1_1']) == 1.0

# Test 2: Singleton with incorrect predictions -> 0.0
assert macro_f05({'S1_1': ['S2_1']}, {'S1_1': []}, ['S1_1']) == 0.0

# Test 3: T=2, k=3 (preds), tp=2 (correct matches)
# Precision = 2/3, Recall = 2/2 = 1.0
# F0.5 = 1.25 * (2/3) * 1 / (0.25 * (2/3) + 1) = 0.83333 / 1.16666 = ~0.71428
test_score = macro_f05({'S1_1': ['S2_1', 'S2_2', 'S2_3']}, {'S1_1': ['S2_1', 'S2_2']}, ['S1_1'])
assert abs(test_score - 0.71428) < 1e-4

print("All metric unit tests passed successfully!")

All metric unit tests passed successfully!

In [13]:
slices_code = """# -*- coding: utf-8 -*-
import polars as pl

def generate_slices():
    # Load full datasets
    tr1 = pl.read_parquet('cache/tr1.parquet')
    tr2 = pl.read_parquet('cache/tr2.parquet')
    tr3 = pl.read_parquet('cache/tr3.parquet')
    gt = pl.read_parquet('cache/ground_truth.parquet')

    # Explode ground truth to make structured lookup mappings
    gt_exploded = gt.with_columns(
        pl.col('matched_entity_ids').str.split(',')
    ).explode('matched_entity_ids')

    # Deduplicate queries to enforce structural constraint that each belongs to at most one target
    gt_exploded = gt_exploded.unique(subset=['matched_entity_ids'])
    gt_exploded.write_parquet('cache/ground_truth_exploded.parquet')

    # Filter geographic samples containing Oregon (US) and Kerala (IN) keywords using 'business_address'
    or_kl_s1 = tr1.filter(
        pl.col('business_address').str.to_lowercase().str.contains(' or ') |
        pl.col('business_address').str.to_lowercase().str.contains(' oregon ') |
        pl.col('business_address').str.to_lowercase().str.contains(' kl ') |
        pl.col('business_address').str.to_lowercase().str.contains(' kerala ')
    )

    s1_ids = or_kl_s1['entity_id'].unique().to_list()

    # Find corresponding queries in ground truth
    mapped_queries = gt_exploded.filter(pl.col('source1_entity_id').is_in(s1_ids))
    query_ids = mapped_queries['matched_entity_ids'].unique().to_list()

    # Slice S2 and S3 resources matching our candidate list
    dev_tr2 = tr2.filter(pl.col('entity_id').is_in(query_ids))
    dev_tr3 = tr3.filter(pl.col('entity_id').is_in(query_ids))

    # Write dev subsets
    or_kl_s1.write_parquet('cache/dev_s1.parquet')
    dev_tr2.write_parquet('cache/dev_s2.parquet')
    dev_tr3.write_parquet('cache/dev_s3.parquet')

    print(f"Slice creation complete: S1_dev={or_kl_s1.height:,}, S2_dev={dev_tr2.height:,}, S3_dev={dev_tr3.height:,}")

if __name__ == '__main__':
    generate_slices()
"""

with open('src/slices.py', 'w') as f:
    f.write(slices_code)

print("src/slices.py written to disk.")

src/slices.py written to disk.

In [19]:
import sys
import importlib
import src.slices
importlib.reload(src.slices)

# Run slice generation
src.slices.generate_slices()

Slice creation complete: S1_dev=96, S2_dev=0, S3_dev=1